// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf C++ Version: 6.33.2

#include "common.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace fluxcache {
namespace proto {

inline constexpr WorkerEndpoint::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        host_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        worker_id_{::uint64_t{0u}},
        port_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR WorkerEndpoint::WorkerEndpoint(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WorkerEndpoint_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WorkerEndpointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WorkerEndpointDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WorkerEndpointDefaultTypeInternal() {}
  union {
    WorkerEndpoint _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WorkerEndpointDefaultTypeInternal _WorkerEndpoint_default_instance_;

inline constexpr FileInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        inode_id_{::uint64_t{0u}},
        size_{::uint64_t{0u}},
        block_size_{::uint64_t{0u}},
        ufs_mtime_ms_{::int64_t{0}},
        is_directory_{false} {}

template <typename>
PROTOBUF_CONSTEXPR FileInfo::FileInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(FileInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileInfoDefaultTypeInternal() {}
  union {
    FileInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileInfoDefaultTypeInternal _FileInfo_default_instance_;
}  // namespace proto
}  // namespace fluxcache
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_common_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_common_2eproto = nullptr;
const ::uint32_t
    TableStruct_common_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::WorkerEndpoint, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::WorkerEndpoint, _impl_.worker_id_),
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::WorkerEndpoint, _impl_.host_),
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::WorkerEndpoint, _impl_.port_),
        1,
        0,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::FileInfo, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::FileInfo, _impl_.inode_id_),
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::FileInfo, _impl_.size_),
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::FileInfo, _impl_.block_size_),
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::FileInfo, _impl_.ufs_mtime_ms_),
        PROTOBUF_FIELD_OFFSET(::fluxcache::proto::FileInfo, _impl_.is_directory_),
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::fluxcache::proto::WorkerEndpoint)},
        {9, sizeof(::fluxcache::proto::FileInfo)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::fluxcache::proto::_WorkerEndpoint_default_instance_._instance,
    &::fluxcache::proto::_FileInfo_default_instance_._instance,
};
const char descriptor_table_protodef_common_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014common.proto\022\017fluxcache.proto\"\?\n\016Worke"
    "rEndpoint\022\021\n\tworker_id\030\001 \001(\004\022\014\n\004host\030\002 \001"
    "(\t\022\014\n\004port\030\003 \001(\r\"j\n\010FileInfo\022\020\n\010inode_id"
    "\030\001 \001(\004\022\014\n\004size\030\002 \001(\004\022\022\n\nblock_size\030\003 \001(\004"
    "\022\024\n\014ufs_mtime_ms\030\004 \001(\003\022\024\n\014is_directory\030\005"
    " \001(\010b\006proto3"
};
static ::absl::once_flag descriptor_table_common_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_common_2eproto = {
    false,
    false,
    212,
    descriptor_table_protodef_common_2eproto,
    "common.proto",
    &descriptor_table_common_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_common_2eproto::offsets,
    file_level_enum_descriptors_common_2eproto,
    file_level_service_descriptors_common_2eproto,
};
namespace fluxcache {
namespace proto {
// ===================================================================

class WorkerEndpoint::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WorkerEndpoint>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_._has_bits_);
};

WorkerEndpoint::WorkerEndpoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WorkerEndpoint_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:fluxcache.proto.WorkerEndpoint)
}
PROTOBUF_NDEBUG_INLINE WorkerEndpoint::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::fluxcache::proto::WorkerEndpoint& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        host_(arena, from.host_) {}

WorkerEndpoint::WorkerEndpoint(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WorkerEndpoint& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WorkerEndpoint_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WorkerEndpoint* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, worker_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, worker_id_),
           offsetof(Impl_, port_) -
               offsetof(Impl_, worker_id_) +
               sizeof(Impl_::port_));

  // @@protoc_insertion_point(copy_constructor:fluxcache.proto.WorkerEndpoint)
}
PROTOBUF_NDEBUG_INLINE WorkerEndpoint::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        host_(arena) {}

inline void WorkerEndpoint::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, worker_id_),
           0,
           offsetof(Impl_, port_) -
               offsetof(Impl_, worker_id_) +
               sizeof(Impl_::port_));
}
WorkerEndpoint::~WorkerEndpoint() {
  // @@protoc_insertion_point(destructor:fluxcache.proto.WorkerEndpoint)
  SharedDtor(*this);
}
inline void WorkerEndpoint::SharedDtor(MessageLite& self) {
  WorkerEndpoint& this_ = static_cast<WorkerEndpoint&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.host_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WorkerEndpoint::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WorkerEndpoint(arena);
}
constexpr auto WorkerEndpoint::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WorkerEndpoint),
                                            alignof(WorkerEndpoint));
}
constexpr auto WorkerEndpoint::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WorkerEndpoint_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WorkerEndpoint::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WorkerEndpoint>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WorkerEndpoint::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WorkerEndpoint>(), &WorkerEndpoint::ByteSizeLong,
              &WorkerEndpoint::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_._cached_size_),
          false,
      },
      &WorkerEndpoint::kDescriptorMethods,
      &descriptor_table_common_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WorkerEndpoint_class_data_ =
        WorkerEndpoint::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WorkerEndpoint::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WorkerEndpoint_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WorkerEndpoint_class_data_.tc_table);
  return WorkerEndpoint_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 43, 2>
WorkerEndpoint::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WorkerEndpoint_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::fluxcache::proto::WorkerEndpoint>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 worker_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(WorkerEndpoint, _impl_.worker_id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_.worker_id_)}},
    // string host = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_.host_)}},
    // uint32 port = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WorkerEndpoint, _impl_.port_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_.port_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 worker_id = 1;
    {PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_.worker_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // string host = 2;
    {PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_.host_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 port = 3;
    {PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_.port_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\36\0\4\0\0\0\0\0"
    "fluxcache.proto.WorkerEndpoint"
    "host"
  }},
};
PROTOBUF_NOINLINE void WorkerEndpoint::Clear() {
// @@protoc_insertion_point(message_clear_start:fluxcache.proto.WorkerEndpoint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.host_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.worker_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.port_) -
        reinterpret_cast<char*>(&_impl_.worker_id_)) + sizeof(_impl_.port_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WorkerEndpoint::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WorkerEndpoint& this_ = static_cast<const WorkerEndpoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WorkerEndpoint::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WorkerEndpoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:fluxcache.proto.WorkerEndpoint)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 worker_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_worker_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_worker_id(), target);
    }
  }

  // string host = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_host().empty()) {
      const ::std::string& _s = this_._internal_host();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "fluxcache.proto.WorkerEndpoint.host");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // uint32 port = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_port() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_port(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fluxcache.proto.WorkerEndpoint)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WorkerEndpoint::ByteSizeLong(const MessageLite& base) {
  const WorkerEndpoint& this_ = static_cast<const WorkerEndpoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WorkerEndpoint::ByteSizeLong() const {
  const WorkerEndpoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:fluxcache.proto.WorkerEndpoint)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string host = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_host().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_host());
      }
    }
    // uint64 worker_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_worker_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_worker_id());
      }
    }
    // uint32 port = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_port() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_port());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WorkerEndpoint::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<WorkerEndpoint*>(&to_msg);
  auto& from = static_cast<const WorkerEndpoint&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:fluxcache.proto.WorkerEndpoint)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_host().empty()) {
        _this->_internal_set_host(from._internal_host());
      } else {
        if (_this->_impl_.host_.IsDefault()) {
          _this->_internal_set_host("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_worker_id() != 0) {
        _this->_impl_.worker_id_ = from._impl_.worker_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_port() != 0) {
        _this->_impl_.port_ = from._impl_.port_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void WorkerEndpoint::CopyFrom(const WorkerEndpoint& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:fluxcache.proto.WorkerEndpoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WorkerEndpoint::InternalSwap(WorkerEndpoint* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.host_, &other->_impl_.host_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_.port_)
      + sizeof(WorkerEndpoint::_impl_.port_)
      - PROTOBUF_FIELD_OFFSET(WorkerEndpoint, _impl_.worker_id_)>(
          reinterpret_cast<char*>(&_impl_.worker_id_),
          reinterpret_cast<char*>(&other->_impl_.worker_id_));
}

::google::protobuf::Metadata WorkerEndpoint::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FileInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FileInfo, _impl_._has_bits_);
};

FileInfo::FileInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:fluxcache.proto.FileInfo)
}
FileInfo::FileInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FileInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE FileInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void FileInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, inode_id_),
           0,
           offsetof(Impl_, is_directory_) -
               offsetof(Impl_, inode_id_) +
               sizeof(Impl_::is_directory_));
}
FileInfo::~FileInfo() {
  // @@protoc_insertion_point(destructor:fluxcache.proto.FileInfo)
  SharedDtor(*this);
}
inline void FileInfo::SharedDtor(MessageLite& self) {
  FileInfo& this_ = static_cast<FileInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FileInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FileInfo(arena);
}
constexpr auto FileInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(FileInfo),
                                            alignof(FileInfo));
}
constexpr auto FileInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FileInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FileInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FileInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FileInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FileInfo>(), &FileInfo::ByteSizeLong,
              &FileInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FileInfo, _impl_._cached_size_),
          false,
      },
      &FileInfo::kDescriptorMethods,
      &descriptor_table_common_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FileInfo_class_data_ =
        FileInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FileInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FileInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FileInfo_class_data_.tc_table);
  return FileInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
FileInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FileInfo, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    FileInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::fluxcache::proto::FileInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 inode_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileInfo, _impl_.inode_id_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.inode_id_)}},
    // uint64 size = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileInfo, _impl_.size_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.size_)}},
    // uint64 block_size = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileInfo, _impl_.block_size_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.block_size_)}},
    // int64 ufs_mtime_ms = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileInfo, _impl_.ufs_mtime_ms_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.ufs_mtime_ms_)}},
    // bool is_directory = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileInfo, _impl_.is_directory_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.is_directory_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 inode_id = 1;
    {PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.inode_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 size = 2;
    {PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.size_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 block_size = 3;
    {PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.block_size_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // int64 ufs_mtime_ms = 4;
    {PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.ufs_mtime_ms_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // bool is_directory = 5;
    {PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.is_directory_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void FileInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:fluxcache.proto.FileInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    ::memset(&_impl_.inode_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.is_directory_) -
        reinterpret_cast<char*>(&_impl_.inode_id_)) + sizeof(_impl_.is_directory_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FileInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FileInfo& this_ = static_cast<const FileInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FileInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FileInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:fluxcache.proto.FileInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 inode_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_inode_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_inode_id(), target);
    }
  }

  // uint64 size = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_size() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_size(), target);
    }
  }

  // uint64 block_size = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_block_size() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_block_size(), target);
    }
  }

  // int64 ufs_mtime_ms = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_ufs_mtime_ms() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_ufs_mtime_ms(), target);
    }
  }

  // bool is_directory = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_is_directory() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          5, this_._internal_is_directory(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fluxcache.proto.FileInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FileInfo::ByteSizeLong(const MessageLite& base) {
  const FileInfo& this_ = static_cast<const FileInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FileInfo::ByteSizeLong() const {
  const FileInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:fluxcache.proto.FileInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // uint64 inode_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_inode_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_inode_id());
      }
    }
    // uint64 size = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_size() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_size());
      }
    }
    // uint64 block_size = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_block_size() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_block_size());
      }
    }
    // int64 ufs_mtime_ms = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_ufs_mtime_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_ufs_mtime_ms());
      }
    }
    // bool is_directory = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_is_directory() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FileInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<FileInfo*>(&to_msg);
  auto& from = static_cast<const FileInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:fluxcache.proto.FileInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_inode_id() != 0) {
        _this->_impl_.inode_id_ = from._impl_.inode_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_size() != 0) {
        _this->_impl_.size_ = from._impl_.size_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_block_size() != 0) {
        _this->_impl_.block_size_ = from._impl_.block_size_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_ufs_mtime_ms() != 0) {
        _this->_impl_.ufs_mtime_ms_ = from._impl_.ufs_mtime_ms_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_is_directory() != 0) {
        _this->_impl_.is_directory_ = from._impl_.is_directory_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FileInfo::CopyFrom(const FileInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:fluxcache.proto.FileInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileInfo::InternalSwap(FileInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.is_directory_)
      + sizeof(FileInfo::_impl_.is_directory_)
      - PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.inode_id_)>(
          reinterpret_cast<char*>(&_impl_.inode_id_),
          reinterpret_cast<char*>(&other->_impl_.inode_id_));
}

::google::protobuf::Metadata FileInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace fluxcache
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_common_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
