// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: master.proto

#include "master.pb.h"
#include "master.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace fluxcache {
namespace proto {

static const char* MasterService_method_names[] = {
  "/fluxcache.proto.MasterService/GetFileInfo",
  "/fluxcache.proto.MasterService/CreateFile",
  "/fluxcache.proto.MasterService/CompleteFile",
  "/fluxcache.proto.MasterService/DeleteFile",
  "/fluxcache.proto.MasterService/Mount",
  "/fluxcache.proto.MasterService/Unmount",
  "/fluxcache.proto.MasterService/ListMounts",
  "/fluxcache.proto.MasterService/RegisterWorker",
  "/fluxcache.proto.MasterService/GetHashRing",
};

std::unique_ptr< MasterService::Stub> MasterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MasterService::Stub> stub(new MasterService::Stub(channel, options));
  return stub;
}

MasterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetFileInfo_(MasterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateFile_(MasterService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CompleteFile_(MasterService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteFile_(MasterService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Mount_(MasterService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Unmount_(MasterService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListMounts_(MasterService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterWorker_(MasterService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetHashRing_(MasterService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MasterService::Stub::GetFileInfo(::grpc::ClientContext* context, const ::fluxcache::proto::GetFileInfoRequest& request, ::fluxcache::proto::GetFileInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::GetFileInfoRequest, ::fluxcache::proto::GetFileInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFileInfo_, context, request, response);
}

void MasterService::Stub::async::GetFileInfo(::grpc::ClientContext* context, const ::fluxcache::proto::GetFileInfoRequest* request, ::fluxcache::proto::GetFileInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::GetFileInfoRequest, ::fluxcache::proto::GetFileInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFileInfo_, context, request, response, std::move(f));
}

void MasterService::Stub::async::GetFileInfo(::grpc::ClientContext* context, const ::fluxcache::proto::GetFileInfoRequest* request, ::fluxcache::proto::GetFileInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFileInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::GetFileInfoResponse>* MasterService::Stub::PrepareAsyncGetFileInfoRaw(::grpc::ClientContext* context, const ::fluxcache::proto::GetFileInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::GetFileInfoResponse, ::fluxcache::proto::GetFileInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFileInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::GetFileInfoResponse>* MasterService::Stub::AsyncGetFileInfoRaw(::grpc::ClientContext* context, const ::fluxcache::proto::GetFileInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFileInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::CreateFile(::grpc::ClientContext* context, const ::fluxcache::proto::CreateFileRequest& request, ::fluxcache::proto::CreateFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::CreateFileRequest, ::fluxcache::proto::CreateFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateFile_, context, request, response);
}

void MasterService::Stub::async::CreateFile(::grpc::ClientContext* context, const ::fluxcache::proto::CreateFileRequest* request, ::fluxcache::proto::CreateFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::CreateFileRequest, ::fluxcache::proto::CreateFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFile_, context, request, response, std::move(f));
}

void MasterService::Stub::async::CreateFile(::grpc::ClientContext* context, const ::fluxcache::proto::CreateFileRequest* request, ::fluxcache::proto::CreateFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::CreateFileResponse>* MasterService::Stub::PrepareAsyncCreateFileRaw(::grpc::ClientContext* context, const ::fluxcache::proto::CreateFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::CreateFileResponse, ::fluxcache::proto::CreateFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::CreateFileResponse>* MasterService::Stub::AsyncCreateFileRaw(::grpc::ClientContext* context, const ::fluxcache::proto::CreateFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::CompleteFile(::grpc::ClientContext* context, const ::fluxcache::proto::CompleteFileRequest& request, ::fluxcache::proto::CompleteFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::CompleteFileRequest, ::fluxcache::proto::CompleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CompleteFile_, context, request, response);
}

void MasterService::Stub::async::CompleteFile(::grpc::ClientContext* context, const ::fluxcache::proto::CompleteFileRequest* request, ::fluxcache::proto::CompleteFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::CompleteFileRequest, ::fluxcache::proto::CompleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CompleteFile_, context, request, response, std::move(f));
}

void MasterService::Stub::async::CompleteFile(::grpc::ClientContext* context, const ::fluxcache::proto::CompleteFileRequest* request, ::fluxcache::proto::CompleteFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CompleteFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::CompleteFileResponse>* MasterService::Stub::PrepareAsyncCompleteFileRaw(::grpc::ClientContext* context, const ::fluxcache::proto::CompleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::CompleteFileResponse, ::fluxcache::proto::CompleteFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CompleteFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::CompleteFileResponse>* MasterService::Stub::AsyncCompleteFileRaw(::grpc::ClientContext* context, const ::fluxcache::proto::CompleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCompleteFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::DeleteFile(::grpc::ClientContext* context, const ::fluxcache::proto::DeleteFileRequest& request, ::fluxcache::proto::DeleteFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::DeleteFileRequest, ::fluxcache::proto::DeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteFile_, context, request, response);
}

void MasterService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::fluxcache::proto::DeleteFileRequest* request, ::fluxcache::proto::DeleteFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::DeleteFileRequest, ::fluxcache::proto::DeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, std::move(f));
}

void MasterService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::fluxcache::proto::DeleteFileRequest* request, ::fluxcache::proto::DeleteFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::DeleteFileResponse>* MasterService::Stub::PrepareAsyncDeleteFileRaw(::grpc::ClientContext* context, const ::fluxcache::proto::DeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::DeleteFileResponse, ::fluxcache::proto::DeleteFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::DeleteFileResponse>* MasterService::Stub::AsyncDeleteFileRaw(::grpc::ClientContext* context, const ::fluxcache::proto::DeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::Mount(::grpc::ClientContext* context, const ::fluxcache::proto::MountRequest& request, ::fluxcache::proto::MountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::MountRequest, ::fluxcache::proto::MountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Mount_, context, request, response);
}

void MasterService::Stub::async::Mount(::grpc::ClientContext* context, const ::fluxcache::proto::MountRequest* request, ::fluxcache::proto::MountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::MountRequest, ::fluxcache::proto::MountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mount_, context, request, response, std::move(f));
}

void MasterService::Stub::async::Mount(::grpc::ClientContext* context, const ::fluxcache::proto::MountRequest* request, ::fluxcache::proto::MountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::MountResponse>* MasterService::Stub::PrepareAsyncMountRaw(::grpc::ClientContext* context, const ::fluxcache::proto::MountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::MountResponse, ::fluxcache::proto::MountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Mount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::MountResponse>* MasterService::Stub::AsyncMountRaw(::grpc::ClientContext* context, const ::fluxcache::proto::MountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::Unmount(::grpc::ClientContext* context, const ::fluxcache::proto::UnmountRequest& request, ::fluxcache::proto::UnmountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::UnmountRequest, ::fluxcache::proto::UnmountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Unmount_, context, request, response);
}

void MasterService::Stub::async::Unmount(::grpc::ClientContext* context, const ::fluxcache::proto::UnmountRequest* request, ::fluxcache::proto::UnmountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::UnmountRequest, ::fluxcache::proto::UnmountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Unmount_, context, request, response, std::move(f));
}

void MasterService::Stub::async::Unmount(::grpc::ClientContext* context, const ::fluxcache::proto::UnmountRequest* request, ::fluxcache::proto::UnmountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Unmount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::UnmountResponse>* MasterService::Stub::PrepareAsyncUnmountRaw(::grpc::ClientContext* context, const ::fluxcache::proto::UnmountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::UnmountResponse, ::fluxcache::proto::UnmountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Unmount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::UnmountResponse>* MasterService::Stub::AsyncUnmountRaw(::grpc::ClientContext* context, const ::fluxcache::proto::UnmountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnmountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::ListMounts(::grpc::ClientContext* context, const ::fluxcache::proto::ListMountsRequest& request, ::fluxcache::proto::ListMountsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::ListMountsRequest, ::fluxcache::proto::ListMountsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListMounts_, context, request, response);
}

void MasterService::Stub::async::ListMounts(::grpc::ClientContext* context, const ::fluxcache::proto::ListMountsRequest* request, ::fluxcache::proto::ListMountsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::ListMountsRequest, ::fluxcache::proto::ListMountsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListMounts_, context, request, response, std::move(f));
}

void MasterService::Stub::async::ListMounts(::grpc::ClientContext* context, const ::fluxcache::proto::ListMountsRequest* request, ::fluxcache::proto::ListMountsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListMounts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ListMountsResponse>* MasterService::Stub::PrepareAsyncListMountsRaw(::grpc::ClientContext* context, const ::fluxcache::proto::ListMountsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::ListMountsResponse, ::fluxcache::proto::ListMountsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListMounts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ListMountsResponse>* MasterService::Stub::AsyncListMountsRaw(::grpc::ClientContext* context, const ::fluxcache::proto::ListMountsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListMountsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::RegisterWorker(::grpc::ClientContext* context, const ::fluxcache::proto::RegisterWorkerRequest& request, ::fluxcache::proto::RegisterWorkerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::RegisterWorkerRequest, ::fluxcache::proto::RegisterWorkerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterWorker_, context, request, response);
}

void MasterService::Stub::async::RegisterWorker(::grpc::ClientContext* context, const ::fluxcache::proto::RegisterWorkerRequest* request, ::fluxcache::proto::RegisterWorkerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::RegisterWorkerRequest, ::fluxcache::proto::RegisterWorkerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterWorker_, context, request, response, std::move(f));
}

void MasterService::Stub::async::RegisterWorker(::grpc::ClientContext* context, const ::fluxcache::proto::RegisterWorkerRequest* request, ::fluxcache::proto::RegisterWorkerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterWorker_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::RegisterWorkerResponse>* MasterService::Stub::PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::fluxcache::proto::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::RegisterWorkerResponse, ::fluxcache::proto::RegisterWorkerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterWorker_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::RegisterWorkerResponse>* MasterService::Stub::AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::fluxcache::proto::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterWorkerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::GetHashRing(::grpc::ClientContext* context, const ::fluxcache::proto::GetHashRingRequest& request, ::fluxcache::proto::GetHashRingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::GetHashRingRequest, ::fluxcache::proto::GetHashRingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetHashRing_, context, request, response);
}

void MasterService::Stub::async::GetHashRing(::grpc::ClientContext* context, const ::fluxcache::proto::GetHashRingRequest* request, ::fluxcache::proto::GetHashRingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::GetHashRingRequest, ::fluxcache::proto::GetHashRingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHashRing_, context, request, response, std::move(f));
}

void MasterService::Stub::async::GetHashRing(::grpc::ClientContext* context, const ::fluxcache::proto::GetHashRingRequest* request, ::fluxcache::proto::GetHashRingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHashRing_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::GetHashRingResponse>* MasterService::Stub::PrepareAsyncGetHashRingRaw(::grpc::ClientContext* context, const ::fluxcache::proto::GetHashRingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::GetHashRingResponse, ::fluxcache::proto::GetHashRingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetHashRing_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::GetHashRingResponse>* MasterService::Stub::AsyncGetHashRingRaw(::grpc::ClientContext* context, const ::fluxcache::proto::GetHashRingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetHashRingRaw(context, request, cq);
  result->StartCall();
  return result;
}

MasterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::fluxcache::proto::GetFileInfoRequest, ::fluxcache::proto::GetFileInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::GetFileInfoRequest* req,
             ::fluxcache::proto::GetFileInfoResponse* resp) {
               return service->GetFileInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::fluxcache::proto::CreateFileRequest, ::fluxcache::proto::CreateFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::CreateFileRequest* req,
             ::fluxcache::proto::CreateFileResponse* resp) {
               return service->CreateFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::fluxcache::proto::CompleteFileRequest, ::fluxcache::proto::CompleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::CompleteFileRequest* req,
             ::fluxcache::proto::CompleteFileResponse* resp) {
               return service->CompleteFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::fluxcache::proto::DeleteFileRequest, ::fluxcache::proto::DeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::DeleteFileRequest* req,
             ::fluxcache::proto::DeleteFileResponse* resp) {
               return service->DeleteFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::fluxcache::proto::MountRequest, ::fluxcache::proto::MountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::MountRequest* req,
             ::fluxcache::proto::MountResponse* resp) {
               return service->Mount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::fluxcache::proto::UnmountRequest, ::fluxcache::proto::UnmountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::UnmountRequest* req,
             ::fluxcache::proto::UnmountResponse* resp) {
               return service->Unmount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::fluxcache::proto::ListMountsRequest, ::fluxcache::proto::ListMountsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::ListMountsRequest* req,
             ::fluxcache::proto::ListMountsResponse* resp) {
               return service->ListMounts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::fluxcache::proto::RegisterWorkerRequest, ::fluxcache::proto::RegisterWorkerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::RegisterWorkerRequest* req,
             ::fluxcache::proto::RegisterWorkerResponse* resp) {
               return service->RegisterWorker(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::fluxcache::proto::GetHashRingRequest, ::fluxcache::proto::GetHashRingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::GetHashRingRequest* req,
             ::fluxcache::proto::GetHashRingResponse* resp) {
               return service->GetHashRing(ctx, req, resp);
             }, this)));
}

MasterService::Service::~Service() {
}

::grpc::Status MasterService::Service::GetFileInfo(::grpc::ServerContext* context, const ::fluxcache::proto::GetFileInfoRequest* request, ::fluxcache::proto::GetFileInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::CreateFile(::grpc::ServerContext* context, const ::fluxcache::proto::CreateFileRequest* request, ::fluxcache::proto::CreateFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::CompleteFile(::grpc::ServerContext* context, const ::fluxcache::proto::CompleteFileRequest* request, ::fluxcache::proto::CompleteFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::DeleteFile(::grpc::ServerContext* context, const ::fluxcache::proto::DeleteFileRequest* request, ::fluxcache::proto::DeleteFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::Mount(::grpc::ServerContext* context, const ::fluxcache::proto::MountRequest* request, ::fluxcache::proto::MountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::Unmount(::grpc::ServerContext* context, const ::fluxcache::proto::UnmountRequest* request, ::fluxcache::proto::UnmountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::ListMounts(::grpc::ServerContext* context, const ::fluxcache::proto::ListMountsRequest* request, ::fluxcache::proto::ListMountsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::RegisterWorker(::grpc::ServerContext* context, const ::fluxcache::proto::RegisterWorkerRequest* request, ::fluxcache::proto::RegisterWorkerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::GetHashRing(::grpc::ServerContext* context, const ::fluxcache::proto::GetHashRingRequest* request, ::fluxcache::proto::GetHashRingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fluxcache
}  // namespace proto
#include <grpcpp/ports_undef.inc>

