// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: worker.proto
#ifndef GRPC_worker_2eproto__INCLUDED
#define GRPC_worker_2eproto__INCLUDED

#include "worker.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace fluxcache {
namespace proto {

// WorkerService provides block-level read/write and heartbeat to clients.
class WorkerService final {
 public:
  static constexpr char const* service_full_name() {
    return "fluxcache.proto.WorkerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::fluxcache::proto::ReadPagesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::ReadPagesResponse>> AsyncReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::ReadPagesResponse>>(AsyncReadPagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::ReadPagesResponse>> PrepareAsyncReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::ReadPagesResponse>>(PrepareAsyncReadPagesRaw(context, request, cq));
    }
    virtual ::grpc::Status BatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::fluxcache::proto::BatchReadPagesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::BatchReadPagesResponse>> AsyncBatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::BatchReadPagesResponse>>(AsyncBatchReadPagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::BatchReadPagesResponse>> PrepareAsyncBatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::BatchReadPagesResponse>>(PrepareAsyncBatchReadPagesRaw(context, request, cq));
    }
    virtual ::grpc::Status WritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::fluxcache::proto::WritePagesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::WritePagesResponse>> AsyncWritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::WritePagesResponse>>(AsyncWritePagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::WritePagesResponse>> PrepareAsyncWritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::WritePagesResponse>>(PrepareAsyncWritePagesRaw(context, request, cq));
    }
    virtual ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::fluxcache::proto::HeartbeatResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::HeartbeatResponse>> AsyncHeartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::HeartbeatResponse>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::HeartbeatResponse>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::HeartbeatResponse>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest* request, ::fluxcache::proto::ReadPagesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest* request, ::fluxcache::proto::ReadPagesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void BatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest* request, ::fluxcache::proto::BatchReadPagesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void BatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest* request, ::fluxcache::proto::BatchReadPagesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void WritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest* request, ::fluxcache::proto::WritePagesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void WritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest* request, ::fluxcache::proto::WritePagesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest* request, ::fluxcache::proto::HeartbeatResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest* request, ::fluxcache::proto::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::ReadPagesResponse>* AsyncReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::ReadPagesResponse>* PrepareAsyncReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::BatchReadPagesResponse>* AsyncBatchReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::BatchReadPagesResponse>* PrepareAsyncBatchReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::WritePagesResponse>* AsyncWritePagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::WritePagesResponse>* PrepareAsyncWritePagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::HeartbeatResponse>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fluxcache::proto::HeartbeatResponse>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::fluxcache::proto::ReadPagesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ReadPagesResponse>> AsyncReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ReadPagesResponse>>(AsyncReadPagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ReadPagesResponse>> PrepareAsyncReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ReadPagesResponse>>(PrepareAsyncReadPagesRaw(context, request, cq));
    }
    ::grpc::Status BatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::fluxcache::proto::BatchReadPagesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::BatchReadPagesResponse>> AsyncBatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::BatchReadPagesResponse>>(AsyncBatchReadPagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::BatchReadPagesResponse>> PrepareAsyncBatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::BatchReadPagesResponse>>(PrepareAsyncBatchReadPagesRaw(context, request, cq));
    }
    ::grpc::Status WritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::fluxcache::proto::WritePagesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::WritePagesResponse>> AsyncWritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::WritePagesResponse>>(AsyncWritePagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::WritePagesResponse>> PrepareAsyncWritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::WritePagesResponse>>(PrepareAsyncWritePagesRaw(context, request, cq));
    }
    ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::fluxcache::proto::HeartbeatResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::HeartbeatResponse>> AsyncHeartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::HeartbeatResponse>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::HeartbeatResponse>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::HeartbeatResponse>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest* request, ::fluxcache::proto::ReadPagesResponse* response, std::function<void(::grpc::Status)>) override;
      void ReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest* request, ::fluxcache::proto::ReadPagesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void BatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest* request, ::fluxcache::proto::BatchReadPagesResponse* response, std::function<void(::grpc::Status)>) override;
      void BatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest* request, ::fluxcache::proto::BatchReadPagesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void WritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest* request, ::fluxcache::proto::WritePagesResponse* response, std::function<void(::grpc::Status)>) override;
      void WritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest* request, ::fluxcache::proto::WritePagesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Heartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest* request, ::fluxcache::proto::HeartbeatResponse* response, std::function<void(::grpc::Status)>) override;
      void Heartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest* request, ::fluxcache::proto::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ReadPagesResponse>* AsyncReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ReadPagesResponse>* PrepareAsyncReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::BatchReadPagesResponse>* AsyncBatchReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::BatchReadPagesResponse>* PrepareAsyncBatchReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::WritePagesResponse>* AsyncWritePagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::WritePagesResponse>* PrepareAsyncWritePagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::HeartbeatResponse>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fluxcache::proto::HeartbeatResponse>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ReadPages_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchReadPages_;
    const ::grpc::internal::RpcMethod rpcmethod_WritePages_;
    const ::grpc::internal::RpcMethod rpcmethod_Heartbeat_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ReadPages(::grpc::ServerContext* context, const ::fluxcache::proto::ReadPagesRequest* request, ::fluxcache::proto::ReadPagesResponse* response);
    virtual ::grpc::Status BatchReadPages(::grpc::ServerContext* context, const ::fluxcache::proto::BatchReadPagesRequest* request, ::fluxcache::proto::BatchReadPagesResponse* response);
    virtual ::grpc::Status WritePages(::grpc::ServerContext* context, const ::fluxcache::proto::WritePagesRequest* request, ::fluxcache::proto::WritePagesResponse* response);
    virtual ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::fluxcache::proto::HeartbeatRequest* request, ::fluxcache::proto::HeartbeatResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReadPages() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::ReadPagesRequest* /*request*/, ::fluxcache::proto::ReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadPages(::grpc::ServerContext* context, ::fluxcache::proto::ReadPagesRequest* request, ::grpc::ServerAsyncResponseWriter< ::fluxcache::proto::ReadPagesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BatchReadPages() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_BatchReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::BatchReadPagesRequest* /*request*/, ::fluxcache::proto::BatchReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchReadPages(::grpc::ServerContext* context, ::fluxcache::proto::BatchReadPagesRequest* request, ::grpc::ServerAsyncResponseWriter< ::fluxcache::proto::BatchReadPagesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WritePages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WritePages() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_WritePages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::WritePagesRequest* /*request*/, ::fluxcache::proto::WritePagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWritePages(::grpc::ServerContext* context, ::fluxcache::proto::WritePagesRequest* request, ::grpc::ServerAsyncResponseWriter< ::fluxcache::proto::WritePagesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Heartbeat() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::HeartbeatRequest* /*request*/, ::fluxcache::proto::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::fluxcache::proto::HeartbeatRequest* request, ::grpc::ServerAsyncResponseWriter< ::fluxcache::proto::HeartbeatResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ReadPages<WithAsyncMethod_BatchReadPages<WithAsyncMethod_WritePages<WithAsyncMethod_Heartbeat<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReadPages() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::fluxcache::proto::ReadPagesRequest, ::fluxcache::proto::ReadPagesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fluxcache::proto::ReadPagesRequest* request, ::fluxcache::proto::ReadPagesResponse* response) { return this->ReadPages(context, request, response); }));}
    void SetMessageAllocatorFor_ReadPages(
        ::grpc::MessageAllocator< ::fluxcache::proto::ReadPagesRequest, ::fluxcache::proto::ReadPagesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fluxcache::proto::ReadPagesRequest, ::fluxcache::proto::ReadPagesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::ReadPagesRequest* /*request*/, ::fluxcache::proto::ReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadPages(
      ::grpc::CallbackServerContext* /*context*/, const ::fluxcache::proto::ReadPagesRequest* /*request*/, ::fluxcache::proto::ReadPagesResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_BatchReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BatchReadPages() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::fluxcache::proto::BatchReadPagesRequest, ::fluxcache::proto::BatchReadPagesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fluxcache::proto::BatchReadPagesRequest* request, ::fluxcache::proto::BatchReadPagesResponse* response) { return this->BatchReadPages(context, request, response); }));}
    void SetMessageAllocatorFor_BatchReadPages(
        ::grpc::MessageAllocator< ::fluxcache::proto::BatchReadPagesRequest, ::fluxcache::proto::BatchReadPagesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fluxcache::proto::BatchReadPagesRequest, ::fluxcache::proto::BatchReadPagesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_BatchReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::BatchReadPagesRequest* /*request*/, ::fluxcache::proto::BatchReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BatchReadPages(
      ::grpc::CallbackServerContext* /*context*/, const ::fluxcache::proto::BatchReadPagesRequest* /*request*/, ::fluxcache::proto::BatchReadPagesResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_WritePages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_WritePages() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::fluxcache::proto::WritePagesRequest, ::fluxcache::proto::WritePagesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fluxcache::proto::WritePagesRequest* request, ::fluxcache::proto::WritePagesResponse* response) { return this->WritePages(context, request, response); }));}
    void SetMessageAllocatorFor_WritePages(
        ::grpc::MessageAllocator< ::fluxcache::proto::WritePagesRequest, ::fluxcache::proto::WritePagesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fluxcache::proto::WritePagesRequest, ::fluxcache::proto::WritePagesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_WritePages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::WritePagesRequest* /*request*/, ::fluxcache::proto::WritePagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WritePages(
      ::grpc::CallbackServerContext* /*context*/, const ::fluxcache::proto::WritePagesRequest* /*request*/, ::fluxcache::proto::WritePagesResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::fluxcache::proto::HeartbeatRequest, ::fluxcache::proto::HeartbeatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fluxcache::proto::HeartbeatRequest* request, ::fluxcache::proto::HeartbeatResponse* response) { return this->Heartbeat(context, request, response); }));}
    void SetMessageAllocatorFor_Heartbeat(
        ::grpc::MessageAllocator< ::fluxcache::proto::HeartbeatRequest, ::fluxcache::proto::HeartbeatResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fluxcache::proto::HeartbeatRequest, ::fluxcache::proto::HeartbeatResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::HeartbeatRequest* /*request*/, ::fluxcache::proto::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::fluxcache::proto::HeartbeatRequest* /*request*/, ::fluxcache::proto::HeartbeatResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ReadPages<WithCallbackMethod_BatchReadPages<WithCallbackMethod_WritePages<WithCallbackMethod_Heartbeat<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReadPages() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::ReadPagesRequest* /*request*/, ::fluxcache::proto::ReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BatchReadPages() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_BatchReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::BatchReadPagesRequest* /*request*/, ::fluxcache::proto::BatchReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WritePages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WritePages() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_WritePages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::WritePagesRequest* /*request*/, ::fluxcache::proto::WritePagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Heartbeat() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::HeartbeatRequest* /*request*/, ::fluxcache::proto::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReadPages() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::ReadPagesRequest* /*request*/, ::fluxcache::proto::ReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadPages(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BatchReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BatchReadPages() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_BatchReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::BatchReadPagesRequest* /*request*/, ::fluxcache::proto::BatchReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchReadPages(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WritePages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WritePages() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_WritePages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::WritePagesRequest* /*request*/, ::fluxcache::proto::WritePagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWritePages(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::HeartbeatRequest* /*request*/, ::fluxcache::proto::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReadPages() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReadPages(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::ReadPagesRequest* /*request*/, ::fluxcache::proto::ReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadPages(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BatchReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BatchReadPages() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->BatchReadPages(context, request, response); }));
    }
    ~WithRawCallbackMethod_BatchReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::BatchReadPagesRequest* /*request*/, ::fluxcache::proto::BatchReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BatchReadPages(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_WritePages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_WritePages() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->WritePages(context, request, response); }));
    }
    ~WithRawCallbackMethod_WritePages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::WritePagesRequest* /*request*/, ::fluxcache::proto::WritePagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WritePages(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Heartbeat(context, request, response); }));
    }
    ~WithRawCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::HeartbeatRequest* /*request*/, ::fluxcache::proto::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReadPages() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fluxcache::proto::ReadPagesRequest, ::fluxcache::proto::ReadPagesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fluxcache::proto::ReadPagesRequest, ::fluxcache::proto::ReadPagesResponse>* streamer) {
                       return this->StreamedReadPages(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::ReadPagesRequest* /*request*/, ::fluxcache::proto::ReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReadPages(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fluxcache::proto::ReadPagesRequest,::fluxcache::proto::ReadPagesResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchReadPages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_BatchReadPages() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fluxcache::proto::BatchReadPagesRequest, ::fluxcache::proto::BatchReadPagesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fluxcache::proto::BatchReadPagesRequest, ::fluxcache::proto::BatchReadPagesResponse>* streamer) {
                       return this->StreamedBatchReadPages(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_BatchReadPages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchReadPages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::BatchReadPagesRequest* /*request*/, ::fluxcache::proto::BatchReadPagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchReadPages(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fluxcache::proto::BatchReadPagesRequest,::fluxcache::proto::BatchReadPagesResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_WritePages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_WritePages() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fluxcache::proto::WritePagesRequest, ::fluxcache::proto::WritePagesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fluxcache::proto::WritePagesRequest, ::fluxcache::proto::WritePagesResponse>* streamer) {
                       return this->StreamedWritePages(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_WritePages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status WritePages(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::WritePagesRequest* /*request*/, ::fluxcache::proto::WritePagesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWritePages(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fluxcache::proto::WritePagesRequest,::fluxcache::proto::WritePagesResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Heartbeat() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fluxcache::proto::HeartbeatRequest, ::fluxcache::proto::HeartbeatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fluxcache::proto::HeartbeatRequest, ::fluxcache::proto::HeartbeatResponse>* streamer) {
                       return this->StreamedHeartbeat(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::fluxcache::proto::HeartbeatRequest* /*request*/, ::fluxcache::proto::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHeartbeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fluxcache::proto::HeartbeatRequest,::fluxcache::proto::HeartbeatResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ReadPages<WithStreamedUnaryMethod_BatchReadPages<WithStreamedUnaryMethod_WritePages<WithStreamedUnaryMethod_Heartbeat<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ReadPages<WithStreamedUnaryMethod_BatchReadPages<WithStreamedUnaryMethod_WritePages<WithStreamedUnaryMethod_Heartbeat<Service > > > > StreamedService;
};

}  // namespace proto
}  // namespace fluxcache


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_worker_2eproto__INCLUDED
