// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: worker.proto

#include "worker.pb.h"
#include "worker.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace fluxcache {
namespace proto {

static const char* WorkerService_method_names[] = {
  "/fluxcache.proto.WorkerService/ReadPages",
  "/fluxcache.proto.WorkerService/BatchReadPages",
  "/fluxcache.proto.WorkerService/WritePages",
  "/fluxcache.proto.WorkerService/Heartbeat",
};

std::unique_ptr< WorkerService::Stub> WorkerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WorkerService::Stub> stub(new WorkerService::Stub(channel, options));
  return stub;
}

WorkerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ReadPages_(WorkerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchReadPages_(WorkerService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WritePages_(WorkerService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Heartbeat_(WorkerService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WorkerService::Stub::ReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::fluxcache::proto::ReadPagesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::ReadPagesRequest, ::fluxcache::proto::ReadPagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadPages_, context, request, response);
}

void WorkerService::Stub::async::ReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest* request, ::fluxcache::proto::ReadPagesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::ReadPagesRequest, ::fluxcache::proto::ReadPagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadPages_, context, request, response, std::move(f));
}

void WorkerService::Stub::async::ReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest* request, ::fluxcache::proto::ReadPagesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadPages_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ReadPagesResponse>* WorkerService::Stub::PrepareAsyncReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::ReadPagesResponse, ::fluxcache::proto::ReadPagesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadPages_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::ReadPagesResponse>* WorkerService::Stub::AsyncReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::ReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadPagesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WorkerService::Stub::BatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::fluxcache::proto::BatchReadPagesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::BatchReadPagesRequest, ::fluxcache::proto::BatchReadPagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchReadPages_, context, request, response);
}

void WorkerService::Stub::async::BatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest* request, ::fluxcache::proto::BatchReadPagesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::BatchReadPagesRequest, ::fluxcache::proto::BatchReadPagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchReadPages_, context, request, response, std::move(f));
}

void WorkerService::Stub::async::BatchReadPages(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest* request, ::fluxcache::proto::BatchReadPagesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchReadPages_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::BatchReadPagesResponse>* WorkerService::Stub::PrepareAsyncBatchReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::BatchReadPagesResponse, ::fluxcache::proto::BatchReadPagesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchReadPages_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::BatchReadPagesResponse>* WorkerService::Stub::AsyncBatchReadPagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::BatchReadPagesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchReadPagesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WorkerService::Stub::WritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::fluxcache::proto::WritePagesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::WritePagesRequest, ::fluxcache::proto::WritePagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WritePages_, context, request, response);
}

void WorkerService::Stub::async::WritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest* request, ::fluxcache::proto::WritePagesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::WritePagesRequest, ::fluxcache::proto::WritePagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WritePages_, context, request, response, std::move(f));
}

void WorkerService::Stub::async::WritePages(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest* request, ::fluxcache::proto::WritePagesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WritePages_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::WritePagesResponse>* WorkerService::Stub::PrepareAsyncWritePagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::WritePagesResponse, ::fluxcache::proto::WritePagesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WritePages_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::WritePagesResponse>* WorkerService::Stub::AsyncWritePagesRaw(::grpc::ClientContext* context, const ::fluxcache::proto::WritePagesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWritePagesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WorkerService::Stub::Heartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::fluxcache::proto::HeartbeatResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fluxcache::proto::HeartbeatRequest, ::fluxcache::proto::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Heartbeat_, context, request, response);
}

void WorkerService::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest* request, ::fluxcache::proto::HeartbeatResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fluxcache::proto::HeartbeatRequest, ::fluxcache::proto::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, std::move(f));
}

void WorkerService::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest* request, ::fluxcache::proto::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::HeartbeatResponse>* WorkerService::Stub::PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fluxcache::proto::HeartbeatResponse, ::fluxcache::proto::HeartbeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Heartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fluxcache::proto::HeartbeatResponse>* WorkerService::Stub::AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::fluxcache::proto::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

WorkerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerService::Service, ::fluxcache::proto::ReadPagesRequest, ::fluxcache::proto::ReadPagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::ReadPagesRequest* req,
             ::fluxcache::proto::ReadPagesResponse* resp) {
               return service->ReadPages(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerService::Service, ::fluxcache::proto::BatchReadPagesRequest, ::fluxcache::proto::BatchReadPagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::BatchReadPagesRequest* req,
             ::fluxcache::proto::BatchReadPagesResponse* resp) {
               return service->BatchReadPages(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerService::Service, ::fluxcache::proto::WritePagesRequest, ::fluxcache::proto::WritePagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::WritePagesRequest* req,
             ::fluxcache::proto::WritePagesResponse* resp) {
               return service->WritePages(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerService::Service, ::fluxcache::proto::HeartbeatRequest, ::fluxcache::proto::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fluxcache::proto::HeartbeatRequest* req,
             ::fluxcache::proto::HeartbeatResponse* resp) {
               return service->Heartbeat(ctx, req, resp);
             }, this)));
}

WorkerService::Service::~Service() {
}

::grpc::Status WorkerService::Service::ReadPages(::grpc::ServerContext* context, const ::fluxcache::proto::ReadPagesRequest* request, ::fluxcache::proto::ReadPagesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WorkerService::Service::BatchReadPages(::grpc::ServerContext* context, const ::fluxcache::proto::BatchReadPagesRequest* request, ::fluxcache::proto::BatchReadPagesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WorkerService::Service::WritePages(::grpc::ServerContext* context, const ::fluxcache::proto::WritePagesRequest* request, ::fluxcache::proto::WritePagesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WorkerService::Service::Heartbeat(::grpc::ServerContext* context, const ::fluxcache::proto::HeartbeatRequest* request, ::fluxcache::proto::HeartbeatResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fluxcache
}  // namespace proto
#include <grpcpp/ports_undef.inc>

